name = "QuantumControlRegistry"
uuid = "4170eb78-06de-4a00-a3e2-ffb5c6cf84a8"
repo = "https://github.com/JuliaQuantumControl/QuantumControlRegistry.git"
description = "A Development-Registry for the JuliaQuantumControl Org"

[packages]
290eba36-e2d8-4488-81b6-f66cc44f2186 = { name = "GRAPELinesearchAnalysis", path = "G/GRAPELinesearchAnalysis" }
a563f35e-61db-434d-8c01-8b9e3ccdfd85 = { name = "QuantumGradientGenerators", path = "Q/QuantumGradientGenerators" }
cad078a0-0012-46f4-b55e-a945d44e115b = { name = "TwoQubitWeylChamber", path = "T/TwoQubitWeylChamber" }
