name = "QuantumControlRegistry"
uuid = "4170eb78-06de-4a00-a3e2-ffb5c6cf84a8"
repo = "https://github.com/JuliaQuantumControl/QuantumControlRegistry.git"
description = "A Development-Registry for the JuliaQuantumControl Org"

[packages]
7bf12567-5742-4b91-a078-644e72a65fc1 = { name = "QuantumPropagators", path = "Q/QuantumPropagators" }
